#!/usr/bin/env python3
"""
emit-hcl.py — aios-export emitter (Phase 1 + Phase 2 module pattern-match).

Reads a tenant snapshot JSON (produced by `tofu output -json tenant_snapshot`
against tools/aios-export/) and emits HCL stubs to stdout.

Phase 1 (default): raw `sg_agent`, `sg_workflow`, and `sg_remote_runner` HCL
stubs. Each emitted resource has a `# Import: terraform import ...` comment
above it so the operator can adopt the resource into Terraform state without
recreation.

Phase 2 (opt-in with --modules-dir <path>): the emitter also reads every
`modules/aios-agent-*/main.tf` under <path> to build a registry of which
canonical agent / workflow names each module creates. Resources in the
snapshot whose name matches a registered module name get rewritten into a
high-level `module "..." { source = ".../aios-agent-X" }` block. Resources
that do not match any module fall back to the raw `sg_*` form. The two
phases are interoperable — `--modules-dir` simply produces nicer output when
the snapshot contains AIOS-shaped agents.

Usage:
    python3 emit-hcl.py [path/to/tenant-snapshot.json]
    python3 emit-hcl.py --modules-dir ../../modules tenant-snapshot.json

If no path is given, JSON is read from stdin.

Companion: tools/aios-export/export.sh wraps `tofu apply` + this script so
solutions engineers run a single command.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from typing import Any, Iterable


# -----------------------------------------------------------------------------
# HCL emit helpers
# -----------------------------------------------------------------------------


def hcl_str(s: Any) -> str:
    """Quote a string for HCL output, preserving newlines via the heredoc form for long strings."""
    if s is None:
        return '""'
    s = str(s)
    if "\n" in s:
        return "<<-EOT\n" + s + "\nEOT"
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def hcl_list(values: Iterable[Any]) -> str:
    items = [hcl_str(v) for v in values if v not in (None, "")]
    if not items:
        return "[]"
    return "[\n    " + ",\n    ".join(items) + ",\n  ]"


def hcl_map(d: dict[str, Any]) -> str:
    if not d:
        return "{}"
    lines = []
    for k, v in d.items():
        if v in (None, ""):
            continue
        lines.append(f'    "{k}" = {hcl_str(v)}')
    if not lines:
        return "{}"
    return "{\n" + "\n".join(lines) + "\n  }"


def safe_tf_id(name: str) -> str:
    """Sanitize a Guild name into a Terraform-legal resource address suffix.

    Collision-unaware: callers that emit multiple addresses of the same
    resource kind should route through a CollisionResolver so two Guild
    names that collapse to the same sanitized form (e.g. "foo-bar" and
    "foo bar" both -> "foo_bar") get unique addresses.
    """
    out = []
    for ch in (name or ""):
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    cleaned = "".join(out).strip("_")
    if not cleaned:
        return "unnamed"
    if cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def _id_suffix(resource_id: Any) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "", str(resource_id or ""))
    return s[-8:] or "x"


class CollisionResolver:
    """Per-resource-kind address allocator that guarantees unique TF addresses.

    On first sight of a sanitized base it returns the base unchanged. On
    subsequent collisions it appends `__<short-id>` (derived from the resource
    id) so the emitted HCL and the generated `import.sh` never produce
    duplicate addresses for the same `sg_*` kind.
    """

    def __init__(self) -> None:
        self._seen: dict[str, int] = {}

    def resolve(self, name: Any, resource_id: Any) -> str:
        base = safe_tf_id(str(name) if name is not None else "")
        count = self._seen.get(base, 0)
        self._seen[base] = count + 1
        if count == 0:
            return base
        return f"{base}__{_id_suffix(resource_id)}"


# -----------------------------------------------------------------------------
# Resource emitters
# -----------------------------------------------------------------------------


def emit_header(snapshot: dict) -> str:
    return (
        "# =============================================================================\n"
        "# Generated by tools/aios-export/ (Phase 1) — do not hand-edit blindly.\n"
        "# =============================================================================\n"
        f"# Source tenant:  {snapshot.get('stackgen_url')}\n"
        f"# Project / org:  {snapshot.get('stackgen_project_id') or '(unscoped)'}\n"
        f"# Captured at:    {snapshot.get('captured_at')}\n"
        f"# Captured by:    {snapshot.get('me', {}).get('email')}"
        f" ({snapshot.get('me', {}).get('id')})\n"
        "#\n"
        "# Phase 1 limitations:\n"
        "#   - Emits raw `sg_*` resources, not idiomatic `module \"...\" {}` blocks.\n"
        "#   - Integrations, policies, schedules, secrets, and webhooks are NOT in the\n"
        "#     data-source surface and therefore NOT exported. Hand-merge those from\n"
        "#     the prior Terraform state, or wait for Phase 2.\n"
        "#   - Run `terraform import sg_<resource>.<addr> <id>` for each resource below\n"
        "#     before `apply` — otherwise Terraform will try to recreate them.\n"
        "# =============================================================================\n\n"
        "terraform {\n"
        "  required_version = \">= 1.5\"\n"
        "  required_providers {\n"
        "    sg = {\n"
        "      source  = \"releases.stackgen.com/stackgen/stackgen\"\n"
        "      version = \">= 0.1.17, < 0.2.0\"\n"
        "    }\n"
        "  }\n"
        "}\n\n"
        "# Configure provider \"sg\" in your root the same way you do today; the export\n"
        "# tool does not emit a provider block to avoid clobbering existing settings.\n\n"
    )


AGENT_PASSTHROUGH = [
    "description",
    "persona",
    "environment",
    "contact_id",
    "parent_agent_id",
    "semantic_router_policy_id",
    "is_router",
]
AGENT_LIST_ATTRS = [
    "model_names",
    "integrations",
    "skills",
    "tools",
    "auto_approve_tools",
    "auto_deny_tools",
    "tags",
    "remote_runners",
]


def emit_agent(agent: dict, resolver: CollisionResolver | None = None) -> str:
    name = agent.get("name") or "unnamed"
    addr = resolver.resolve(name, agent.get("id")) if resolver else safe_tf_id(name)
    out = [
        f"# Agent: {name}",
        f"# Import: terraform import sg_agent.{addr} {agent.get('id')}",
        f'resource "sg_agent" "{addr}" {{',
        f'  name = {hcl_str(name)}',
    ]
    for attr in AGENT_PASSTHROUGH:
        val = agent.get(attr)
        if val in (None, "", False):
            continue
        if attr == "is_router":
            out.append(f"  {attr} = {str(bool(val)).lower()}")
        else:
            out.append(f"  {attr} = {hcl_str(val)}")
    for attr in AGENT_LIST_ATTRS:
        val = agent.get(attr) or []
        if val:
            out.append(f"  {attr} = {hcl_list(val)}")
    out.append("}")
    out.append("")
    return "\n".join(out)


WORKFLOW_PASSTHROUGH = [
    "description",
    "domain",
    "escalation_policy_ref",
    "evidence_checklist_ref",
]
WORKFLOW_LIST_ATTRS = [
    "tags",
    "example_queries",
    "required_inputs",
    "optional_inputs",
    "runbook_refs",
    "remediation_pattern_refs",
]


def emit_workflow(wf: dict, resolver: CollisionResolver | None = None) -> str:
    name = wf.get("name") or "unnamed"
    addr = resolver.resolve(name, wf.get("id")) if resolver else safe_tf_id(name)
    out = [
        f"# Workflow: {name} (version {wf.get('version')}, status {wf.get('status')})",
        f"# Import: terraform import sg_workflow.{addr} {wf.get('id')}",
        f'resource "sg_workflow" "{addr}" {{',
        f'  name = {hcl_str(name)}',
    ]
    for attr in WORKFLOW_PASSTHROUGH:
        val = wf.get(attr)
        if val in (None, ""):
            continue
        out.append(f"  {attr} = {hcl_str(val)}")
    for attr in WORKFLOW_LIST_ATTRS:
        val = wf.get(attr) or []
        if val:
            out.append(f"  {attr} = {hcl_list(val)}")
    out.append("}")
    out.append("")
    return "\n".join(out)


RUNNER_PASSTHROUGH = ["description"]
RUNNER_LIST_ATTRS = ["capabilities", "attached_agents"]


def emit_runner(runner: dict, resolver: CollisionResolver | None = None) -> str:
    name = runner.get("name") or "unnamed"
    addr = resolver.resolve(name, runner.get("id")) if resolver else safe_tf_id(name)
    out = [
        f"# Remote runner: {name} (status {runner.get('status')}, last heartbeat {runner.get('last_heartbeat')})",
        f"# Import: terraform import sg_remote_runner.{addr} {runner.get('id')}",
        f'resource "sg_remote_runner" "{addr}" {{',
        f'  name = {hcl_str(name)}',
    ]
    for attr in RUNNER_PASSTHROUGH:
        val = runner.get(attr)
        if val in (None, ""):
            continue
        out.append(f"  {attr} = {hcl_str(val)}")
    for attr in RUNNER_LIST_ATTRS:
        val = runner.get(attr) or []
        if val:
            out.append(f"  {attr} = {hcl_list(val)}")
    labels = runner.get("labels") or {}
    if labels:
        out.append(f"  labels = {hcl_map(labels)}")
    out.append("}")
    out.append("")
    return "\n".join(out)


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------


def load_snapshot(path: str | None) -> dict:
    if path:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    return json.load(sys.stdin)


# -----------------------------------------------------------------------------
# Phase 2 — module pattern matching
# -----------------------------------------------------------------------------
#
# Each modules/aios-agent-*/main.tf registers a fixed set of `sg_agent` and
# `sg_workflow` resources with stable canonical names. We parse those names
# out of each module's main.tf and, at emit time, collapse matching groups of
# snapshot resources back into a single `module "..." { ... }` block.
#
# Heuristic: a module matches when AT LEAST ONE of its canonical agent OR
# workflow names appears in the snapshot. Partial matches still emit the
# module block plus a comment listing which canonical names were missing so
# the operator can investigate. Strict-match (require all names) is opt-in
# via --strict-match.


_AGENT_RE = re.compile(
    r'resource\s+"sg_agent"\s+"[^"]+"\s*\{[^}]*?\bname\s*=\s*"([^"]+)"',
    re.DOTALL,
)
_WORKFLOW_RE = re.compile(
    r'resource\s+"sg_workflow"\s+"[^"]+"\s*\{[^}]*?\bname\s*=\s*"([^"]+)"',
    re.DOTALL,
)


def build_module_registry(modules_dir: str) -> dict[str, dict[str, set[str]]]:
    """Scan modules/aios-agent-*/main.tf and return a registry:
        { module_name: { "agents": {names}, "workflows": {names}, "path": str } }
    """
    registry: dict[str, dict[str, set[str] | str]] = {}
    if not modules_dir or not os.path.isdir(modules_dir):
        return registry
    for entry in sorted(os.listdir(modules_dir)):
        if not entry.startswith("aios-agent-"):
            continue
        main_tf = os.path.join(modules_dir, entry, "main.tf")
        if not os.path.isfile(main_tf):
            continue
        try:
            with open(main_tf, "r", encoding="utf-8") as f:
                src = f.read()
        except OSError:
            continue
        agents = set(_AGENT_RE.findall(src))
        workflows = set(_WORKFLOW_RE.findall(src))
        if not agents and not workflows:
            continue
        registry[entry] = {
            "agents": agents,
            "workflows": workflows,
            "path": os.path.relpath(os.path.join(modules_dir, entry), start="."),
        }
    return registry


def match_modules(snapshot: dict, registry: dict, strict: bool) -> tuple[list[dict], set[str], set[str]]:
    """Return (matches, consumed_agent_names, consumed_workflow_names).

    Each `matches` entry: {module, present_agents, present_workflows, missing_agents, missing_workflows, path}
    """
    snap_agent_names = {a.get("name") for a in (snapshot.get("agents") or []) if a.get("name")}
    snap_wf_names = {w.get("name") for w in (snapshot.get("workflows") or []) if w.get("name")}

    consumed_agents: set[str] = set()
    consumed_workflows: set[str] = set()
    matches: list[dict] = []

    for mod_name, info in registry.items():
        canon_agents = info["agents"]
        canon_workflows = info["workflows"]
        present_agents = canon_agents & snap_agent_names
        present_workflows = canon_workflows & snap_wf_names
        if not present_agents and not present_workflows:
            continue
        if strict:
            missing = (canon_agents - present_agents) | (canon_workflows - present_workflows)
            if missing:
                continue
        matches.append({
            "module": mod_name,
            "path": info["path"],
            "present_agents": sorted(present_agents),
            "present_workflows": sorted(present_workflows),
            "missing_agents": sorted(canon_agents - present_agents),
            "missing_workflows": sorted(canon_workflows - present_workflows),
        })
        consumed_agents |= present_agents
        consumed_workflows |= present_workflows
    return matches, consumed_agents, consumed_workflows


def emit_module_block(match: dict) -> str:
    addr = safe_tf_id(match["module"])
    out = [
        f"# Module match: {match['module']}",
        f"#   present agents:     {', '.join(match['present_agents']) or '(none)'}",
        f"#   present workflows:  {', '.join(match['present_workflows']) or '(none)'}",
    ]
    if match["missing_agents"] or match["missing_workflows"]:
        out.append(
            "#   missing (NOT in snapshot — investigate or pin module version that omits them):"
        )
        for n in match["missing_agents"]:
            out.append(f"#     - agent:    {n}")
        for n in match["missing_workflows"]:
            out.append(f"#     - workflow: {n}")
    out.append(
        f'#   Run `terraform import` for each present resource to adopt remote state.'
    )
    out.append(f'module "{addr}" {{')
    out.append(f'  source = "{match["path"]}"')
    out.append('')
    out.append('  # Wire these from your foundation / policies / integration modules.')
    out.append('  # The exporter cannot infer them from the read-only data source surface.')
    out.append('  model_names       = module.foundation.model_names')
    out.append('  policy_ids        = module.policies.policy_ids')
    out.append('  integration_names = {}')
    out.append('}')
    out.append('')
    return "\n".join(out)


def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("snapshot", nargs="?", help="Path to tenant-snapshot.json (default: stdin).")
    p.add_argument(
        "--modules-dir",
        default=None,
        help="Path to the directory containing aios-agent-* modules. When set, "
             "matched groups are rewritten as `module \"...\" {}` blocks (Phase 2).",
    )
    p.add_argument(
        "--strict-match",
        action="store_true",
        help="Only collapse a module when every canonical agent + workflow name is present.",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])
    raw = load_snapshot(args.snapshot)
    snap = raw.get("value", raw)

    registry = build_module_registry(args.modules_dir) if args.modules_dir else {}
    matches, consumed_agents, consumed_workflows = match_modules(snap, registry, args.strict_match)

    out = [emit_header(snap)]

    # Per-kind address allocators. Two Guild names that sanitize to the same
    # base (e.g. "foo-bar" and "foo bar" -> "foo_bar") would otherwise emit
    # duplicate `resource "sg_agent" "foo_bar"` blocks; the resolver appends a
    # short id-derived suffix on the second+ occurrence to keep addresses
    # unique. The companion logic in tools/aios-export/export.sh mirrors this
    # so the generated import.sh stays in lockstep.
    agent_resolver = CollisionResolver()
    workflow_resolver = CollisionResolver()
    runner_resolver = CollisionResolver()

    if registry:
        out.append(
            "# -----------------------------------------------------------------------------\n"
            f"# Phase 2 module pattern-match (registry from {args.modules_dir})\n"
            "# -----------------------------------------------------------------------------\n"
            "# Matched aios-agent-* modules go first; raw resources that did not match any\n"
            "# module follow.\n"
        )
        if not matches:
            out.append("# (no module matches — falling back to raw sg_* emit only)\n")
        for m in matches:
            out.append(emit_module_block(m))

    out.append(
        "# -----------------------------------------------------------------------------\n"
        "# Agents" + (" (excluding those collapsed into module blocks above)" if matches else "") + "\n"
        "# -----------------------------------------------------------------------------\n"
    )
    agents = [a for a in (snap.get("agents") or []) if a.get("name") not in consumed_agents]
    if not agents:
        out.append("# (no unmatched agents)\n" if matches else "# (no agents in snapshot)\n")
    for a in agents:
        out.append(emit_agent(a, agent_resolver))

    out.append(
        "# -----------------------------------------------------------------------------\n"
        "# Workflows" + (" (excluding those collapsed into module blocks above)" if matches else "") + "\n"
        "# -----------------------------------------------------------------------------\n"
    )
    workflows = [w for w in (snap.get("workflows") or []) if w.get("name") not in consumed_workflows]
    if not workflows:
        out.append("# (no unmatched workflows)\n" if matches else "# (no workflows in snapshot)\n")
    for w in workflows:
        out.append(emit_workflow(w, workflow_resolver))

    out.append(
        "# -----------------------------------------------------------------------------\n"
        "# Remote runners\n"
        "# -----------------------------------------------------------------------------\n"
    )
    runners = snap.get("remote_runners") or []
    if not runners:
        out.append("# (no remote runners in snapshot)\n")
    for r in runners:
        out.append(emit_runner(r, runner_resolver))

    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
