#!/usr/bin/env bash
# =============================================================================
# tools/aios-export/export.sh — Phase 1 wrapper
# =============================================================================
# One-command export of a StackGen tenant.
#
# Read-only against the tenant. Writes to ./out/ in this directory.
#
# Usage:
#   STACKGEN_URL=...  STACKGEN_TOKEN=...  ./export.sh
#   STACKGEN_URL=...  STACKGEN_TOKEN=...  STACKGEN_PROJECT_ID=...  ./export.sh
#
# Output files:
#   out/tenant-snapshot.json    Raw data-source dump (apt for diffs across customers).
#   out/tenant.tf               HCL stubs for sg_agent / sg_workflow / sg_remote_runner.
#   out/import.sh               One-line `terraform import` per emitted resource.
#
# The Terraform root contains only `data "sg_*"` blocks, so `tofu apply` is a
# no-op apply that just refreshes data. No state is changed in the tenant.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${ROOT}/out"
mkdir -p "${OUT}"

if [[ -z "${STACKGEN_URL:-}" ]]; then
  echo "error: STACKGEN_URL is required" >&2
  exit 2
fi
if [[ -z "${STACKGEN_TOKEN:-}" ]]; then
  echo "error: STACKGEN_TOKEN is required" >&2
  exit 2
fi

export TF_VAR_stackgen_url="${STACKGEN_URL}"
export TF_VAR_stackgen_token="${STACKGEN_TOKEN}"
export TF_VAR_stackgen_project_id="${STACKGEN_PROJECT_ID:-}"

if command -v tofu >/dev/null 2>&1; then
  TF=tofu
elif command -v terraform >/dev/null 2>&1; then
  TF=terraform
else
  echo "error: neither tofu nor terraform on PATH" >&2
  exit 2
fi

echo "==> ${TF} init in ${ROOT}"
( cd "${ROOT}" && "${TF}" init -input=false -upgrade )

echo "==> ${TF} apply (read-only — no resources to create)"
( cd "${ROOT}" && "${TF}" apply -input=false -auto-approve )

echo "==> Writing ${OUT}/tenant-snapshot.json"
( cd "${ROOT}" && "${TF}" output -json tenant_snapshot ) > "${OUT}/tenant-snapshot.json"

echo "==> Writing ${OUT}/tenant.tf"
if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 is required for the HCL emitter" >&2
  exit 2
fi
# Phase 1 (raw sg_* resources only):
python3 "${ROOT}/emit-hcl.py" "${OUT}/tenant-snapshot.json" > "${OUT}/tenant.tf"

# Phase 2 (collapse matched groups into module blocks):
# Emitted to a separate file so the operator can compare; choose whichever
# representation they prefer to commit to the customer's repo.
MODULES_DIR="${MODULES_DIR:-${ROOT}/../../modules}"
if [[ -d "${MODULES_DIR}" ]]; then
  echo "==> Writing ${OUT}/tenant.modules.tf (Phase 2 — module pattern-match)"
  python3 "${ROOT}/emit-hcl.py" --modules-dir "${MODULES_DIR}" "${OUT}/tenant-snapshot.json" \
    > "${OUT}/tenant.modules.tf"
else
  echo "==> Skipping Phase 2 — modules dir not found at ${MODULES_DIR}"
fi

echo "==> Writing ${OUT}/import.sh"
python3 - "${OUT}/tenant-snapshot.json" > "${OUT}/import.sh" <<'PY'
import json, sys
raw = json.load(open(sys.argv[1]))
snap = raw.get("value", raw)
print("#!/usr/bin/env bash")
print("# Generated by tools/aios-export/export.sh")
print("# Run from the root that contains the emitted tenant.tf.")
print("set -euo pipefail")
print('TF="${TF:-tofu}"')
def safe(name):
    out = [c if (c.isalnum() or c == "_") else "_" for c in (name or "unnamed")]
    s = "".join(out).strip("_") or "unnamed"
    return ("_" + s) if s[0].isdigit() else s
for a in snap.get("agents") or []:
    print(f'"$TF" import sg_agent.{safe(a.get("name"))} {a.get("id")}')
for w in snap.get("workflows") or []:
    print(f'"$TF" import sg_workflow.{safe(w.get("name"))} {w.get("id")}')
for r in snap.get("remote_runners") or []:
    print(f'"$TF" import sg_remote_runner.{safe(r.get("name"))} {r.get("id")}')
PY
chmod +x "${OUT}/import.sh"

agent_count="$("${TF}" -chdir="${ROOT}" output -raw agent_count 2>/dev/null || echo 0)"
workflow_count="$("${TF}" -chdir="${ROOT}" output -raw workflow_count 2>/dev/null || echo 0)"
runner_count="$("${TF}" -chdir="${ROOT}" output -raw remote_runner_count 2>/dev/null || echo 0)"

cat <<SUMMARY

Export complete.

  out/tenant-snapshot.json   ${agent_count} agents, ${workflow_count} workflows, ${runner_count} remote runners.
  out/tenant.tf              HCL stubs for the above (raw sg_* resources, Phase 1).
  out/import.sh              One terraform import per resource — run in the target root before \`apply\`.

Next steps:
  1. Copy out/tenant.tf into the customer's repo (or a fresh root).
  2. Configure provider "sg" in that root (this tool does not emit a provider block).
  3. Run out/import.sh from the same root to bring each resource under Terraform management.
  4. Hand-merge integrations / policies / schedules / secrets — Phase 1 does not export those.

Phase 2 (separate workstream) will rewrite groups of related resources into idiomatic
module "..." { source = ".../aios-agent-*" } blocks.

SUMMARY
