#!/usr/bin/env bash
# =============================================================================
# tools/aios-export/export.sh — Phase 1 wrapper
# =============================================================================
# One-command export of a StackGen tenant.
#
# Read-only against the tenant. Writes user-facing artifacts to ./out/ in this
# directory; Terraform working files (.terraform/, .terraform.lock.hcl, local
# state) are kept out of the repo working tree by staging the .tf files into
# a temp work dir and running every tofu/terraform command from there.
#
# Usage:
#   STACKGEN_URL=...  STACKGEN_TOKEN=...  ./export.sh
#   STACKGEN_URL=...  STACKGEN_TOKEN=...  STACKGEN_PROJECT_ID=...  ./export.sh
#
# Output files (all under tools/aios-export/out/):
#   out/tenant-snapshot.json    Raw data-source dump (apt for diffs across customers).
#   out/tenant.tf               HCL stubs for sg_agent / sg_workflow / sg_remote_runner.
#   out/tenant.modules.tf       (if modules/ is reachable) Phase 2 module pattern-match output.
#   out/import.sh               One-line `terraform import` per emitted resource.
#
# Working-state files (kept entirely outside the repo; deleted after the run
# unless KEEP_TF_WORK=1):
#   $TMPDIR/aios-export-XXXX/*.tf                   symlinks to tools/aios-export/*.tf
#   $TMPDIR/aios-export-XXXX/.terraform/            provider plugin cache
#   $TMPDIR/aios-export-XXXX/.terraform.lock.hcl    provider lockfile
#   $TMPDIR/aios-export-XXXX/terraform.tfstate      ephemeral state (data-source only)
#
# The Terraform root contains only `data "sg_*"` blocks, so `tofu apply` is a
# no-op apply that just refreshes data. No state is changed in the tenant.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${ROOT}/out"
mkdir -p "${OUT}"

# Keep Terraform's working artifacts out of the repo working tree. The root
# is data-source only, so we stage the .tf files into a fresh temp work dir
# via symlinks and run every `tofu`/`terraform` command from there. That way
# .terraform/, .terraform.lock.hcl, and terraform.tfstate all live under the
# temp dir and never touch tools/aios-export/.
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/aios-export-XXXXXX")"
for f in "${ROOT}"/*.tf; do
  [[ -f "${f}" ]] && ln -s "${f}" "${WORK_DIR}/$(basename "${f}")"
done

cleanup() {
  if [[ "${KEEP_TF_WORK:-0}" == "1" ]]; then
    echo "==> KEEP_TF_WORK=1; leaving Terraform working dir at ${WORK_DIR}" >&2
  else
    rm -rf "${WORK_DIR}"
  fi
}
trap cleanup EXIT

if [[ -z "${STACKGEN_URL:-}" ]]; then
  echo "error: STACKGEN_URL is required" >&2
  exit 2
fi
if [[ -z "${STACKGEN_TOKEN:-}" ]]; then
  echo "error: STACKGEN_TOKEN is required" >&2
  exit 2
fi

export TF_VAR_stackgen_url="${STACKGEN_URL}"
export TF_VAR_stackgen_token="${STACKGEN_TOKEN}"
export TF_VAR_stackgen_project_id="${STACKGEN_PROJECT_ID:-}"

if command -v tofu >/dev/null 2>&1; then
  TF=tofu
elif command -v terraform >/dev/null 2>&1; then
  TF=terraform
else
  echo "error: neither tofu nor terraform on PATH" >&2
  exit 2
fi

echo "==> ${TF} init in ${WORK_DIR}"
( cd "${WORK_DIR}" && "${TF}" init -input=false -upgrade )

echo "==> ${TF} apply (read-only — no resources to create)"
( cd "${WORK_DIR}" && "${TF}" apply -input=false -auto-approve )

echo "==> Writing ${OUT}/tenant-snapshot.json"
( cd "${WORK_DIR}" && "${TF}" output -json tenant_snapshot ) > "${OUT}/tenant-snapshot.json"

echo "==> Writing ${OUT}/tenant.tf"
if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 is required for the HCL emitter" >&2
  exit 2
fi
# Phase 1 (raw sg_* resources only):
python3 "${ROOT}/emit-hcl.py" "${OUT}/tenant-snapshot.json" > "${OUT}/tenant.tf"

# Phase 2 (collapse matched groups into module blocks):
# Emitted to a separate file so the operator can compare; choose whichever
# representation they prefer to commit to the customer's repo.
MODULES_DIR="${MODULES_DIR:-${ROOT}/../../modules}"
if [[ -d "${MODULES_DIR}" ]]; then
  echo "==> Writing ${OUT}/tenant.modules.tf (Phase 2 — module pattern-match)"
  python3 "${ROOT}/emit-hcl.py" --modules-dir "${MODULES_DIR}" "${OUT}/tenant-snapshot.json" \
    > "${OUT}/tenant.modules.tf"
else
  echo "==> Skipping Phase 2 — modules dir not found at ${MODULES_DIR}"
fi

echo "==> Writing ${OUT}/import.sh"
python3 - "${OUT}/tenant-snapshot.json" > "${OUT}/import.sh" <<'PY'
import json, re, sys
raw = json.load(open(sys.argv[1]))
snap = raw.get("value", raw)
print("#!/usr/bin/env bash")
print("# Generated by tools/aios-export/export.sh")
print("# Run from the root that contains the emitted tenant.tf.")
print("set -euo pipefail")
print('TF="${TF:-tofu}"')

# Sanitize a Guild name into a Terraform resource address suffix. Must stay
# in lockstep with the equivalent function in emit-hcl.py so the emitted HCL
# and these import addresses line up. Per-resource-kind collision tracker:
# multiple Guild names can sanitize to the same address (e.g. "foo-bar" and
# "foo bar" both collapse to "foo_bar"), so when that happens we append a
# short, deterministic id-derived suffix to make every address unique.
def _base(name):
    chars = [c if (c.isalnum() or c == "_") else "_" for c in (name or "unnamed")]
    s = "".join(chars).strip("_") or "unnamed"
    return ("_" + s) if s[0].isdigit() else s

def _id_suffix(resource_id):
    s = re.sub(r"[^A-Za-z0-9]+", "", str(resource_id or ""))
    return s[-8:] or "x"

def make_resolver():
    seen = {}
    def resolve(name, resource_id):
        base = _base(name)
        if base not in seen:
            seen[base] = 1
            return base
        seen[base] += 1
        return f"{base}__{_id_suffix(resource_id)}"
    return resolve

agent_addr = make_resolver()
workflow_addr = make_resolver()
runner_addr = make_resolver()

for a in snap.get("agents") or []:
    print(f'"$TF" import sg_agent.{agent_addr(a.get("name"), a.get("id"))} {a.get("id")}')
for w in snap.get("workflows") or []:
    print(f'"$TF" import sg_workflow.{workflow_addr(w.get("name"), w.get("id"))} {w.get("id")}')
for r in snap.get("remote_runners") or []:
    print(f'"$TF" import sg_remote_runner.{runner_addr(r.get("name"), r.get("id"))} {r.get("id")}')
PY
chmod +x "${OUT}/import.sh"

agent_count="$("${TF}" -chdir="${WORK_DIR}" output -raw agent_count 2>/dev/null || echo 0)"
workflow_count="$("${TF}" -chdir="${WORK_DIR}" output -raw workflow_count 2>/dev/null || echo 0)"
runner_count="$("${TF}" -chdir="${WORK_DIR}" output -raw remote_runner_count 2>/dev/null || echo 0)"

cat <<SUMMARY

Export complete.

  out/tenant-snapshot.json   ${agent_count} agents, ${workflow_count} workflows, ${runner_count} remote runners.
  out/tenant.tf              HCL stubs for the above (raw sg_* resources, Phase 1).
  out/import.sh              One terraform import per resource — run in the target root before \`apply\`.

Next steps:
  1. Copy out/tenant.tf into the customer's repo (or a fresh root).
  2. Configure provider "sg" in that root (this tool does not emit a provider block).
  3. Run out/import.sh from the same root to bring each resource under Terraform management.
  4. Hand-merge integrations / policies / schedules / secrets — Phase 1 does not export those.

Phase 2 (separate workstream) will rewrite groups of related resources into idiomatic
module "..." { source = ".../aios-agent-*" } blocks.

SUMMARY
